### PR TITLE
Add Scala 3 build

### LINKED ISSUE #14: Add Scala 3 build
See: https://github.com/trace4cats/trace4cats/issues/229

### PR DESCRIPTION
**Pull request by catostrophe**
Closes #14

There are some compile errors which I'm trying to handle.

cc @ybasket

### CODE REVIEW

**Comment by catostrophe** [comment]
I fought the typer and the typer won...

**Comment by catostrophe** [comment]
We need help from a dotty hacker to get through this blocker.

**Comment by ybasket** [comment]
I gave it a try and failed as well – not a ZIO user though, maybe someone out there knows their ways around `Has` on Scala 3…

**Comment by catostrophe** [comment]
I also fixed some other minor issues that never appeared in real code but became visible during my experiments.

**Review by janstenpickle — APPROVED** [review]

**Pull request merged**
